### ISSUE TITLE
Request: change text of @button

### ISSUE THREAD

**Issue by hcharp** [saxix/django-admin-extra-buttons#4]
Hello and thank you for this necessary django library :)

I wish I could rename a button, here, the "Refresh" button, for example "Mettre à jour", etc.

Thank you :)

**Comment by hcharp** [comment]
Ok nevermind, I found it by testing: changing the name of the function "refresh" to "mettre_a_jour" works well (did not test the 'à' characters but it's enough for an MVP ^^)

**Comment by Upgreydd** [comment]
add `label` to decorator
