### ISSUE TITLE
Add the possibility to download a file from a button handler

### ISSUE THREAD

**Issue by sronveaux** [saxix/django-admin-extra-buttons#9]
Hello,

I have a case where I'd like a button to download a file by returning a FileResponse. However, the current code checks if something else than a HttpResponse is given and Redirects in that case :

https://github.com/saxix/django-admin-extra-buttons/blob/778c94cfa7b40b30bce68bae808859d9bf4e0cb5/src/admin_extra_buttons/handlers.py#L52-L54

I made a quick and dirty patch locally to test replacing line 52 with `if not isinstance(ret, (FileResponse, HttpResponse)):` and this did the trick for me.

I wondered if there was something else I wasn't aware of and if there was a reason not to give the opportunity to send back files from your excellent Django app. Otherwise, would you mind if I open a PR with this modification ?

Thanks for the excellent work,
Cheers

Sébastien

**Comment by adrian-parisi** [comment]
Hello,

I have exactly the same issue with **StreamingHttpResponse**. In my case, I need a button to download a huge zip file which needs to be streamed to the client.

Can you please add support for it as well?

Thanks!
Adrian

**Comment by tvanesse** [comment]
Same here, I need to return a `FileResponse`. Happy to contribute to the PR if that's still on the table.
